<?php
$title = "Terms and Conditions";
$page = 'terms-and-conditions';
include('header.php');
?>
<div _ngcontent-giu-c1="" class=" container-fluid deal-blog">
   <div _ngcontent-giu-c1="" class="container">
      <div _ngcontent-giu-c1="" class="row">
         <div _ngcontent-giu-c1="" class="col-md-12 com-lg-8" id="terms-and-condition">
            <div _ngcontent-giu-c1="" class="deal-detail text-left">
               <h3 _ngcontent-giu-c1=""></h3>
               <p _ngcontent-giu-c1="" class="deal-p"></p>
               <div _ngcontent-giu-c1="" class="page-body deal-detail">
                  <h3 _ngcontent-giu-c1="">TERMS AND CONDITIONS OF USE</h3>
                  <div _ngcontent-giu-c1="">
                     <p _ngcontent-giu-c1="" lang="en-GB"><span _ngcontent-giu-c1="" style="font-family: 'Calibri Light', serif;"><span _ngcontent-giu-c1="" style="font-size: xx-large;"><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="" style="font-size: medium;"><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""></strong></u></span></span></span></span></p>
                     <p _ngcontent-giu-c1=""><br _ngcontent-giu-c1=""></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">This is a contract between you and Render Health Technology Limited ("Render Health"), a private limited company incorporated in Nigeria. Please read these terms and conditions carefully, they are intended to explain our obligations to you, as well as your obligations, and are binding on any use of the Platform provided to you by Render Health.</strong></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">OVERVIEW</strong></u></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">Render Health Patient Portal </strong></span><span _ngcontent-giu-c1="">("web platform"), is operated by </span><span _ngcontent-giu-c1="">Render Health Technology Ltd.</span><span _ngcontent-giu-c1=""> References in this agreement to "Render Health", "we", "our" or "us", are to Render Health Technology Ltd depending on the context, and references to "you" or "your" are to the persons with whom Render Health enters into this agreement. Render Health offers the Platform, including all information, tools and services available on it to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated here.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health Technology Limited, on behalf of itself and its affiliates/group companies under the brand "Render Health " (</span></span><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">"Render"</span></strong></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">), is the author and publisher of the internet resource </span></span><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><a _ngcontent-giu-c1="" routerlink="/" ng-reflect-router-link="/" href="#/"><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">www.renderhealth.com</span></span></a></u></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">").Render Health owns and operates the services provided through the Website.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">These Terms of Service apply to all users of the Platform or any other Render Health platform including, without limitation, users who are browsers, vendors, customers, merchants, and/ or contributors of content. </span><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">By visiting our Platform</strong></span><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">or any other Render Health platform, you agree to be bound by the following terms and conditions "Terms/Terms of Service"), including the additional terms and conditions and policies referenced herein.</strong></span><span _ngcontent-giu-c1=""> If you do not agree to all the Terms then you may not access the Platform or make use of any of our services. </span></span></p>
                     <p _ngcontent-giu-c1=""><br _ngcontent-giu-c1=""></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">DISCLAIMER</strong></u></span></span></p>
                     <p _ngcontent-giu-c1="">&nbsp;</p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website (including, without limitation, any warranties implied by law in respect of satisfactory quality, fitness for purpose and/or the use of reasonable care and skill). </span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Nothing in this disclaimer will limit or exclude our or your liability for death or personal injury resulting from negligence; limit or exclude our or your liability for fraud or fraudulent misrepresentation; limit any of our or your liabilities in any way that is not permitted under applicable law; or exclude any of our or your liabilities that may not be excluded under applicable law.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The limitations and exclusions of liability set out in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer or in relation to the subject matter of this disclaimer, including liabilities arising in contract, in tort (including negligence) and for breach of statutory duty.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">To the extent that the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature. </span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 1 - GENERAL CONDITIONS </strong></u></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">We reserve the </span><span _ngcontent-giu-c1="">right to </span><span _ngcontent-giu-c1="">refuse </span><span _ngcontent-giu-c1="">service </span><span _ngcontent-giu-c1="">to anyone for any reason at any time. By agreeing to these Terms, you represent that you are at least of </span><span _ngcontent-giu-c1="">the </span><span _ngcontent-giu-c1="">age of consent in Nigeria.</span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The Terms apply</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> to you whether you are -</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">A medical practitioner or health care provider, Fitness or Wellness instructor or facility, Diagnostic Centre (whether an individual professional or an organization) or similar institution wishing to be listed, or already listed, on the Website, including designated, authorized associates of such practitioners or institutions&nbsp;</span></span><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">("Practitioner(s)", "you" or "User");</span></strong></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">&nbsp;or</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">A patient, his/her representatives or affiliates, searching for Practitioners through the Website&nbsp;</span></span><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">("End-User", "you" or "User");</span></strong></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">&nbsp;or</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Otherwise a user of the Website&nbsp;</span></span><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">("you" or "User")</span></strong></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">This Agreement applies to those services made available by Render Health on the Website, which are offered free of charge to the Users&nbsp;</span></span><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">("Services")</span></strong></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">, including the following:</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">For Practitioners: Listing of Practitioners and their profiles and contact details, to be made available to the other Users and visitors to the Website;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">For other Users: Facility to (i) create and maintain 'Health Accounts', (ii) search for Practitioners by name, specialty, and geographical area, or any other criteria that may be developed and made available by Render Health, and (iii) to make appointments with Healthcare Specialist.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The Services may change from time to time, at the sole discretion of Render Health, and the Agreement will apply to your visit to and your use of the Website to avail the Service, as well as to all information provided by you on the Website at any given point in time.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">This terms and conditions </span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">define the conditions </span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">under which you are allowed to use the Website and </span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">describe</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> the manner in which we shall treat your account while you are registered as a member with us. </span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">By downloading or accessing the Website to use the Services, you irrevocably accept all the conditions stipulated in this Agreement, the&nbsp;</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Subscription Terms of Service</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">&nbsp;and&nbsp;</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Privacy Policy</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">, as available on the Website, and agree to abide by them. </span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The Terms and Conditions supersede</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> all previous oral and written terms and conditions (if any) communicated to you relating to your use of the Website to avail the Services. By availing any Service, you signify your acceptance of the terms of this Agreement.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">We reserve the right to modify or terminate any portion of the Agreement for any reason and at any time, and such modifications shall be informed to you in writing</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">.</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> You should read the Agreement at regular intervals. Your use of the Website following any such modification constitutes your agreement to follow and be bound by the Agreement so modified.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">You acknowledge that you will be bound by this Agreement for availing any of the Services offered by us. If you do not agree with any part of the Agreement, please do not use the Website or avail any Services.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Your access to use of the Website and the Services will be solely at the discretion of Render Health.</span></span></p>
                     <p _ngcontent-giu-c1="">&nbsp;</p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION </strong></u></span><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">2</strong></u></span><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> - </strong></u></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">CONDITIONS OF USE</strong></u></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">You must be 18 years of age or older to register, use the Services, or visit or use the Website in any manner. By registering, visiting and using the Website or accepting this Agreement, you represent and warrant to Render Health that you are 18 years of age or older, and that you have the right, authority and capacity to use the Website and the Services available through the Website, and agree to and abide by this Agreement.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION </strong></u></span><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">3</strong></u></span><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> - </strong></u></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">TERMS OF USE APPLICABLE TO ALL USERS OTHER THAN PRACTITIONERS</strong></u></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The terms in this Clause 3 are applicable only to Users other than Practitioners.</span></span></p>
                     <p _ngcontent-giu-c1=""><br _ngcontent-giu-c1=""></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">END</strong></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">-USER ACCOUNT AND DATA PRIVACY</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health may by its Services, collect information relating to the devices through which you access the Website, and anonymous data of your usage. The collected information will be used only for improving the quality of Render Health services and to build new services.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">&nbsp;<span _ngcontent-giu-c1="">The Website allows Render Health to have access to registered Users' personal email or phone number, for communication purpose so as to provide you a better way of booking appointments and for obtaining feedback in relation to the Practitioners and their practice.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">&nbsp;<span _ngcontent-giu-c1="">The User is expected to read and understand the Privacy Policy, so as to ensure that he or she has the knowledge of,&nbsp;</span></span><span _ngcontent-giu-c1=""><em _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">inter-alia</span></em></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">:</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> fact that certain information is being collected</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> purpose for which the information is being collected;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> intended recipients of the information;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> nature of collection and retention of the information; and</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> name and address of the agency that is collecting the information and the agency that will retain the information; and</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> various rights available to such Users in respect of such information.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health shall not be responsible in any manner for the authenticity of the personal information or sensitive personal data or information supplied by the User to Render Health or to any other person acting on behalf of Render Health.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">&nbsp;<span _ngcontent-giu-c1="">The User is responsible for maintaining the confidentiality of the User's account access information and password, if the User is registered on the Website. The User shall be responsible for all usage of the User's account and password, whether or not authorized by the User. The User shall immediately notify Render Health of any actual or suspected unauthorized use of the User's account or password. Although Render health will not be liable for your losses caused by any unauthorized use of your account, you may be liable for the losses of Render Health or such other parties as the case may be, due to any unauthorized use of your account.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">If</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> a User provides any information that is untrue, inaccurate, not current or incomplete (or becomes untrue, inaccurate, not current or incomplete), or Render Health has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Render Health has the right to discontinue the Services to the User at its sole discretion.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health may use such information collected from the Users from time to time for the purposes of debugging customer support related issues.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">RELEVANCE</strong></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> ALGORITHM</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health's relevance algorithm for the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre is a fully automated system that lists the Practitioners, their profile and information regarding their Practice on its Website. These listings of Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's do not represent any fixed objective ranking or endorsement by Render Health. Render Health will not be liable for any change in the relevance of the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's on search results, which may take place from time to time. The listing of Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's will be based on automated computation of the various factors including inputs made by the Users including their comments and feedback. Such factors may change from time to time, in order to improve the listing algorithm. Render Health in no event will be held responsible for the accuracy and the relevancy of the listing order of the Practitioners on the Website.</span></span></p>
                     <p _ngcontent-giu-c1=""><br _ngcontent-giu-c1=""></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">LISTING</strong></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> CONTENT AND DISSEMINATING INFORMATION</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health collects, directly or indirectly, and displays on the Website, relevant information regarding the profile and practice of the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre listed on the Website, such as their specialization, qualification, fees, location, visiting hours, and similar details. Render Health takes reasonable efforts to ensure that such information is updated at frequent intervals. Although Render Health screens and vets the information and photos submitted by the Practitioners, it cannot be held liable for any inaccuracies or incompleteness represented from it, despite such reasonable efforts.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Services provided by Render Health or any of its partners or service providers are provided on an "as is" and "as available' basis, and without any warranties or conditions (express or implied, including the implied warranties of merchantability, accuracy, fitness for a particular purpose, title and non-infringement, arising by statute or otherwise in law or from a course of dealing or usage or trade). Render Health does not provide or make any representation, warranty or guarantee, express or implied about the Website or the Services. Render Health does not guarantee the accuracy or completeness of any content or information provided by Users on the Website. To the fullest extent permitted by law, Render Health disclaims all liability arising out of the User's use or reliance upon the Website, the Services, representations and warranties made by other Users, the content or information provided by the Users on the Website, or any opinion or suggestion given or expressed by Render Health or any User in relation to any User or services provided by such User.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Website may be linked to the website of third parties, affiliates and business partners. Render Health has no control over, and not liable or responsible for content, accuracy, validity, reliability, quality of such websites or made available by/through our Website. Inclusion of any link on the Website does not imply that Render Health endorses the linked site. User may use the links and these services at User's own risk.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health assumes no responsibility, and shall not be liable for, any damages to, or viruses that may infect User's equipment on account of User's access to, use of, or browsing the Website or the downloading of any material, data, text, images, video content, or audio content from the Website. If a User is dissatisfied with the Website, User's sole remedy is to discontinue using the Website.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">If</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Render Health determines that you have provided fraudulent, inaccurate, or incomplete information, including through feedback, Render Health reserves the right to immediately suspend your access to the Website or any of your accounts with Render Health and makes such declaration on the website alongside your name/your clinic's name as determined by Render Health for the protection of its business and in the interests of Users. You shall be liable to indemnify Render Health for any losses incurred as a result of your misrepresentations or fraudulent feedback that has adversely affected Render Health or its Users.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">BOOK</strong></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> APPOINTMENT</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health enables Users to connect with Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre through booking facility that allows Users book an appointment through the Website</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">. </span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health will ensure Users are provided confirmed appointment on the Book facility. However, Render Health has no liability if such an appointment is later cancelled by the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's, or the same Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's is not available for appointment. </span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> results of any search Users perform on the Website for Practitioners should not be construed as an endorsement by Render Health of any such particular Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's. If the User decides to engage with a Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's to seek services, the User shall be doing so at his/her own risk.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Without prejudice to the generality of the above, Render Health is not involved in providing any healthcare or medical advice or diagnosis and hence is not responsible for any interactions between User and the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's. User understands and agrees that Render Health will not be liable for:</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">User interactions and associated issues User has with the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre ;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">the ability or intent of the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's or the lack of it, in fulfilling their obligations towards Users;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">any wrong medication or quality of treatment being given by the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre, or any medical negligence on part of the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's ;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">inappropriate treatment, or similar difficulties or any type of inconvenience suffered by the User due to a failure on the part of the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's to provide agreed Services;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">any misconduct or inappropriate behaviour by the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's or the P Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's staff;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">cancellation or no show by the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's or rescheduling of booked appointment or any variation in the fees charged.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Users</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> are allowed to provide feedback about their experiences with the Practitioner, however, the User shall ensure that, the same is provided in accordance with applicable law. User however understands that, Render Health shall not be obliged to act in such manner as may be required to give effect to the content of Users feedback, such as suggestions for delisting of a particular Practitioner from the Website.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">NO</strong></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> DOCTOR-PATIENT RELATIONSHIP; NOT FOR EMERGENCY USE</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Please</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> note that some of the content, text, data, graphics, images, information, suggestions, guidance, and other material (collectively, "Information") that may be available on the Website (including information provided in direct response to your questions or postings) may be provided by individuals in the medical profession. The provision of such Information does not create a licensed medical professional/patient relationship, between Render Health and you and does not constitute an opinion, medical advice, or diagnosis or treatment of any particular condition, but is only provided to assist you with locating appropriate medical care from a qualified practitioner.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">It</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> is hereby expressly clarified that, the Information that you obtain or receive from Render Health, and its employees, contractors, partners, sponsors, advertisers, licensors or otherwise on the Website is for informational purposes only. We make no guarantees, representations or warranties, whether expressed or implied, with respect to professional qualifications, quality of work, expertise or other information provided on the Website. In no event shall we be liable to you or anyone else for any decision made or action taken by you in reliance on such information.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Services are not intended to be a substitute for getting in touch with emergency healthcare. If you are an End-User facing a medical emergency (either on your or a another person's behalf), please contact an ambulance service or hospital directly.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">CONTENT</strong></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> OWNERSHIP AND COPYRIGHT CONDITIONS OF ACCESS</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> contents listed on the Website are (i) User generated content, or (ii) belong to Render Health. The information that is collected by Render Health directly or indirectly from the End- Users and the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's shall belong to Render Health. Copying of the copyrighted content published by Render Health on the Website for any commercial purpose or for the purpose of earning profit will be a violation of copyright and Render Health reserves its rights under applicable law accordingly.</span></span></p>
                     <p _ngcontent-giu-c1=""><br _ngcontent-giu-c1=""></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health authorizes the User to view and access the content available on or from the Website solely for ordering, receiving, delivering and communicating only as per this Agreement. The contents of the Website, information, text, graphics, images, logos, button icons, software code, design, and the collection, arrangement and assembly of content on the Website are the property of Render Health and are protected under copyright, trademark and other laws. User shall not modify the Render Health Content or reproduce, display, publicly perform, distribute, or otherwise use the Render Health Content in any way for any public or commercial purpose or for personal gain.</span></span></p>
                     <p _ngcontent-giu-c1="">&nbsp;</p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">User</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> shall not access the Services for purposes of monitoring their availability, performance or functionality, or for any other benchmarking or competitive purposes.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 4- REVIEWS</strong></u></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> AND FEEDBACK</strong></u></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">By using this Website, you agree that any information shared by you with Render Health or with any Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's will be subject to our Privacy Policy.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">You are solely responsible for the content that you choose to submit for publication on the Website, including any feedback, ratings, or reviews ("Critical Content") relating to Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's or other healthcare professionals. The role of Render Health in publishing Critical Content is restricted to that of an 'intermediary' under the Information Technology Act, 2000. Render Health disclaims all responsibility with respect to the content of Critical Content, and its role with respect to such content is restricted to its obligations as an 'intermediary' under the said Act. Render Health shall not be liable to pay any consideration to any User for re-publishing any content across any of its platforms.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 5-</strong></u></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> HEALTH DIARY &amp; HEALTH RECORD</strong></u></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health provide End-Users with a free facility known as 'Health Diary' on its web application which allows users store actions about how they feel on a daily basis</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health provides End-Users with Health Record access which allows users view health records that have been uploaded and enter to their patient profile if permission has been granted by the healthcare facility</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Information from your "Health Diary" can be attached to your medical appointments for Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's to see and use for diagnosis.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The specific terms relating to such Health Account are as below, without prejudice to the rest of these Terms and the Privacy Policy:</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Your</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Records is only created after you have signed up and explicitly accepted these Terms.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Any</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Practice created Health Record is provided on an as-is basis at the sole intent, risk and responsibility of the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's and Render Health does not validate the said information and makes no representation in connection therewith. You should contact the relevant Practitioner in case you wish to point out any discrepancies or add, delete, or modify the Health Record in any manner.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health Records are provided on an as-is basis. While we strive to maintain the highest levels of service availability, Render Health is not liable for any interruption that may be caused to your access of the Services.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">It</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> is your responsibility to keep your correct mobile number and email ID updated in the Records. The Health Records will be sent to the Records associated with this mobile number and/or email ID. Every time you change any contact information (mobile or email), we will send a confirmation. Render Health is not responsible for any loss or inconvenience caused due to your failure in updating the contact details with Render Health.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health uses industry-level security and encryption to your Health Records. However, Render Health does not guarantee to prevent unauthorized access if you lose your login credentials or they are otherwise compromised. In the event you are aware of any unauthorized use or access, you shall immediately inform Render Health of such unauthorized use or access. Please safeguard your login credentials and report any actual suspected breach of account to </span></span><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><a _ngcontent-giu-c1="" href="mailto:contact@renderhealth.com">contact@renderhealth.com</a></u></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">If</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> you access your dependents' Health Records by registering your dependents with your own Records, you are deemed to be responsible for the Health Records of your dependents and all obligations that your dependents would have had, had they maintained their own separate individual Records. You agree that it shall be your sole responsibility to obtain prior consent of your dependent and shall have right to share, upload and publish any sensitive personal information of your dependent. Render health assumes no responsibility for any claim, dispute or liability arising in this regard, and you shall indemnify Render Health and its officers against any such claim or liability arising out of unauthorized use of such information.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">In</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> case you want to delete your Records, you can do so by contacting our service support team or the facility in which your health record is store. However only your account and any associated Health Records will be deleted, and your Health Records stored by your Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's will continue to be stored in their respective accounts.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">You</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> may lose your "User created" record, if the data is not synced with the server.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">If</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> the Health Record is unassessed for a stipulated time, you may not be able to access your Health Records due to security reasons.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health is not liable if for any reason, Health Records are not delivered to you or are delivered late despite its best efforts.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health Records are shared with the phone numbers that are provided by your Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre. Render Health is not responsible for adding the Heath Records with incorrect numbers if those incorrect numbers are provided by the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health is not responsible or liable for any content, fact, Health Records, medical deduction or the language used in your Health Records whatsoever. Your Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre. is solely responsible and liable for your Health Records and any information provided to us including but not limited to the content in them.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health has the ability in its sole discretion to retract Health Records without any prior notice if they are found to be shared incorrectly or inadvertently.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health will follow the law of land in case of any constitutional court or jurisdiction mandates to share the Health Records for any reason.</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> You</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> agree and acknowledge that Render Health may need to access the Health Record for cases such as any technical or operational issue of the End User in access or ownership of the Records.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">You</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> acknowledge that the Practitioners you are visiting may engage Render Health's software or third party software for the purposes of the functioning of the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's business and Render Health's services including but not limited to the usage and for storage of Records.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">To</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> the extent that your Records have been shared with Render Health or stored on any of the Render Health products used by Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre. you are visiting, and may in the past have visited, You hereby agree to the storage of your Records by Render Health pertaining to such previously visited clinics and hospitals who have tie ups with Render Health for the purposes of their business and for Render Health's services including but not limited to the usage and for storage of Records. Upon creation of your account with Render Health, to the mapping of such Records as may be available in Render Health's database to your User account.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">SECTION 6 - </span></strong></u></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">&nbsp;TERMS OF USE FOR </strong></u></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SPECIALIST, FITNESS &amp; WELLNESS INSTRUCTOR/ FACILITIES OR DIAGNOSTICS CENTRE</strong></u></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The terms in this Clause </span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">6</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> are applicable only to Practitioners.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">LISTING POLICY</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health, directly and indirectly, collects information regarding the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre profiles, contact details, and practice. Render Health reserves the right to take down any Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre profile as well as the right to display the profile of the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre with or without notice to the concerned Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre. This information is collected for the purpose of facilitating interaction with the End-Users and other Users. If any information displayed on the Website in connection with you and your profile is found to be incorrect, you are required to inform Render Health immediately to enable Render Health to make the necessary amendments.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health shall not be liable and responsible for the ranking of the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre on external websites and search engines</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health shall not be responsible or liable in any manner to the Users for any losses, damage, injuries or expenses incurred by the Users as a result of any disclosures or publications made by Render Health where the User has expressly or implicitly consented to the making of disclosures or publications by Render Health. If the User had revoked such consent under the terms of the Privacy Policy, then Render Health shall not be responsible or liable in any manner to the User for any losses, damage, injuries or expenses incurred by the User as a result of any disclosures made by Render Health prior to its actual receipt of such revocation.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health reserves the right to moderate the suggestions made by the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre through feedback and the right to remove any abusive or inappropriate or promotional content added on the Website. However, Render Health shall not be liable if any inactive, inaccurate, fraudulent, or non- existent profiles of Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre are added to the Website if after initial vetting as been done.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre explicitly agree that Render Health reserves the right to publish the Content provided by Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre to a third party including content platforms.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">You</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> as a Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre hereby represent and warrant that you will use the Services in accordance with applicable law. Any contravention of applicable law as a result of your use of these Services is your sole responsibility, Render Health accepts no liability for the same.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">6.2 </span></strong></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">PROFILE</strong></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> OWNERSHIP AND EDITING RIGHTS</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health ensures easy access to the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre by providing a tool to update your profile information by contact your client representative for your facility. Render Health reserves the right of ownership of all the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's profile and photographs and to moderate the changes or updates requested by Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre. However, Render Health takes the independent decision whether to publish or reject the requests submitted for the respective changes or updates. You hereby represent and warrant that you are fully entitled under law to upload all content uploaded by you as part of your profile or otherwise while using Render Health's services, and that no such content breaches any third party rights, including intellectual property rights. Upon becoming aware of a breach of the foregoing representation, Render Health may modify or delete parts of your profile information at its sole discretion with or without notice to you.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">RELEVANCE</strong></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> ALGORITHM</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health has designed the relevance algorithm in the best interest of the End-User and may adjust the relevance algorithm from time to time to improve the quality of the results given to the patients. It is a pure merit driven, proprietary algorithm which cannot be altered for specific Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre. Render Health shall not be liable for any effect on the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's business interests due to the change in the Relevance Algorithm.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">6.3 INDEPENDENT</strong></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> SERVICES</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Your use of each Service confers upon you only the rights and obligations relating to such Service, and not to any other service that may be provided by Render Health.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">6.4 RENDER</strong></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> HEALTH REACH RIGHTS</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health reserves the rights to display sponsored ads on the Website. These ads would be marked as "Sponsored ads". Without prejudice to the status of other content, Render Health will not be liable for the accuracy of information or the claims made in the Sponsored ads. Render Health does not encourage the Users to visit the Sponsored ads page or to avail any services from them. Render Health will not be liable for the services of the providers of the Sponsored ads.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">You represent and warrant that you will use these Services in accordance with applicable law. Any contravention of applicable law as a result of your use of these Services is your sole responsibility, and </span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> accepts no liability for the same.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">BOOK APPOINTMENT </strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">As</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> a valuable partner on our platform we want to ensure that the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre experience on the Render Health booking platform is beneficial to both, P Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre and their Users.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre understands that, Render Health shall not be liable, under any event, for any comments or feedback given by any of the Users in relation to the Services provided by Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre. The option of publishing or modifying or moderating or masking (where required by law or norm etc.) the feedback provided by Users shall be solely at the discretion of Render Health.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">&nbsp;</span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SPECIALIST, FITNESS</strong></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> AND </strong></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">WELLNESS INSTRUCTOR/FACILITY or DIAGNOSIS CENTRE UNDERTAKING</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre is and shall be duly registered, licensed and qualified to practice medicine/ provide health care, wellness services, as per applicable laws/regulations/guidelines set out by competent authorities and the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre shall not be part of any arrangement which will prohibit him/her from practicing medicine within the Federal Republic of Nigeria. The Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre shall at all times ensure that all the applicable laws that govern the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre shall be followed and utmost care shall be taken in terms of the consultation/ services being rendered.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">&nbsp;</span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">USAGE IN PROMOTIONAL &amp; MARKETING MATERIALS</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">In recognition of the various offerings and services provided by Render Health to Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre, Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre shall (subject to its reasonable right to review and approve): </span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">(a) allow Render Health to include a brief description of the services provided to Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre in Render Health's marketing, promotional and advertising materials; </span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">(b) allow Render Health to make reference to Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre in case studies, and related marketing materials; </span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">(c) serve as a reference to Render Health's existing and potential clients; </span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">(d) provide video logs, testimonials, e-mailers, banners, interviews to the news media and provide quotes for press releases; </span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">(e) make presentations at conferences; and/or </span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">(f) use the Specialist, Fitness &amp; Wellness instructor/ facilities or Diagnostics Centre's name and/or logo, brand images, tag lines etc., within product literature, e-mailers, press releases, social media and other advertising, marketing and promotional materials.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 7 - </strong></u></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">RIGHTS AND OBLIGATIONS RELATING TO CONTENT</strong></u></span></span></p>
                     <p _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">7.1 Render</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health hereby informs Users that they are not permitted to host, display, upload, modify, publish, transmit, update or share any information that:</span></span></strong></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">belongs to another person and to which the User does not have any right to;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">harm minors in any way;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">infringes any patent, trademark, copyright or other proprietary rights;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">violates any law for the time being in force;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">impersonate another person;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">threatens the unity, integrity, defence, security of the Federal Republic of Nigeria, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Users</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> are also prohibited from:</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">violating or attempting to violate the integrity or security of the Website or any Render Health Content;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">transmitting any information (including job posts, messages and hyperlinks) on or through the Website that is disruptive or competitive to the provision of Services by Render Health;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">intentionally submitting on the Website any incomplete, false or inaccurate information;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">making any unsolicited communications to other Users;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">using any engine, software, tool, agent or other device or mechanism (such as spiders, robots, avatars or intelligent agents) to navigate or search the Website;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">attempting to decipher, decompile, disassemble or reverse engineer any part of the Website;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">copying or duplicating in any manner any of the Render Health Content or other information available from the Website;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">framing or hot linking or deep linking any Render Health Content.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">circumventing or disabling any digital rights management, usage rules, or other security features of the Software.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">In</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> case of non-compliance with any applicable laws, rules or regulations, or the Agreement (including the Privacy Policy) by a User, Render Health has the right to immediately terminate the access or usage rights of the User to the Website and Services and to remove non-compliant information from the Website.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health may disclose or transfer User-generated information to its affiliates or governmental authorities in such manner as permitted or required by applicable law, and you hereby consent to such transfer. The SPI Rules only permit Render health to transfer sensitive personal data or information including any information, to any other body corporate or a person in Nigeria, or located in any other country, that ensures the same level of data protection that is adhered to by Render Health as provided for under the SPI Rules, only if such transfer is necessary for the performance of the lawful contract between Render Health or any person on its behalf and the User or where the User has consented to data transfer.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health respects the intellectual property rights of others and we do not hold any responsibility for any violations of any intellectual property rights</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">TERMINATION</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">8.1 Render</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Health reserves the right to suspend or terminate a User's access to the Website and the Services with or without notice and to exercise any other remedy available under law, in cases where,</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Such User breaches any terms and conditions of the Agreement;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">A third party reports violation of any of its right as a result of your use of the Services;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health is unable to verify or authenticate any information provide to Render Health by a User;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health has reasonable grounds for suspecting any illegal, fraudulent or abusive activity on part of such User; or</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health believes in its sole discretion that User's actions may cause legal liability for such User, other Users or for Render Health or are contrary to the interests of the Website.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Once</span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> temporarily suspended, indefinitely suspended or terminated, the User may not continue to use the Website under the same account, a different account or re-register under a new account. On termination of an account due to the reasons mentioned herein, such User shall no longer have access to data, messages, files and other material kept on the Website by such User. The User shall ensure that he/she/it has continuous backup of any medical services the User has rendered in order to comply with the User's record keeping process and practices.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 9 - </strong></u></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">LIMITATION OF LIABILITY</strong></u></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">In no event, including but not limited to negligence, shall Render Health, or any of its directors, officers, employees, agents or content or service providers (collectively, the "Protected Entities") be liable for any direct, indirect, special, incidental, consequential, exemplary or punitive damages arising from, or directly or indirectly related to, the use of, or the inability to use, the Website or the content, materials and functions related thereto, the Services, User's provision of information via the Website, lost business or lost End-Users, even if such Protected Entity has been advised of the possibility of such damages. In no event shall the Protected Entities be liable for:</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">provision of or failure to provide all or any service by Practitioners to End- Users contacted or managed through the Website;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">any content posted, transmitted, exchanged or received by or on behalf of any User or other person on or through the Website;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">any unauthorized access to or alteration of your transmissions or data; or</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">any other matter relating to the Website or the Service.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 10 - INTELLECTUAL PROPERTY </strong></u></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> 10.1 Unless otherwise stated, Render Health Technology Limited and/or it's licensors own the intellectual property rights for all material on Render Health Technology Limited. All intellectual property rights are reserved. You may view and/or print pages from <a _ngcontent-giu-c1="" routerlink="/" ng-reflect-router-link="/" href="#/">http://www.renderhealth.com</a> for your own personal use subject to restrictions set in these terms and conditions.</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">You must not: </span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">Republish material from </strong></span></span><span _ngcontent-giu-c1=""><a _ngcontent-giu-c1="" routerlink="/" ng-reflect-router-link="/" href="#/">http://www.renderhealth.com</a></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">Sell, rent or sub-license material from <a _ngcontent-giu-c1="" routerlink="/" ng-reflect-router-link="/" href="#/">http://www.renderhealth.com</a></strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">Reproduce, duplicate or copy material from </strong></span></span><span _ngcontent-giu-c1=""><a _ngcontent-giu-c1="" routerlink="/" ng-reflect-router-link="/" href="#/">http://www.renderhealth.com</a></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Redistribute content from Render Health Technology Limited (unless content is specifically made for redistribution).</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">User Comments</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Certain parts of this website offer the opportunity for users to post and exchange opinions, information, material and data ('Comments') in areas of the website. Render Health Technology Limited does not screen, edit, publish or review Comments prior to their appearance on the website and Comments do not reflect the views or opinions of Render Health Technology Limited, its agents or affiliates. Comments reflect the view and opinion of the person who posts such view or opinion. To the extent permitted by applicable laws Render Health Technology Limited shall not be responsible or liable for the Comments or for any loss cost, liability, damages or expenses caused and or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Render Health Technology Limited reserves the right to monitor all Comments and to remove any Comments which it considers in its absolute discretion to be inappropriate, offensive or otherwise in breach of these Terms and Conditions.</span></span></p>
                     <p _ngcontent-giu-c1=""><br _ngcontent-giu-c1=""></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">You warrant and represent that:</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The Comments do not infringe any intellectual property right, including without limitation copyright, patent or trademark, or other proprietary right of any third party;</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material or material which is an invasion of privacy</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">You hereby grant to Render Health Technology Limited a non-exclusive royalty-free license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media. </span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">No use of Render Health Technology Limited's logo or other artwork will be allowed for linking absent a trademark license agreement.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""></span></span><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1=""> 10.3 Reservation of Rights</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">We reserve the right at any time and in its sole discretion to request that you remove all links or any particular link to our Web site. You agree to immediately remove all links to our Web site upon such request. We also reserve the right to amend these terms and conditions and its linking policy at any time. By continuing to link to our Web site, you agree to be bound to and abide by these linking terms and conditions.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Removal of links from our website If you find any link on our Web site or any linked web site objectionable for any reason, you may contact us about this. We will consider requests to remove links but will have no obligation to do so or to respond directly to you.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Whilst we endeavor to ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we commit to ensuring that the website remains available or that the material on the website is kept up to date.</span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">10.4 Content Liability</strong></span></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">We shall have no responsibility or liability for any content appearing on your Web site. You agree to indemnify and defend us against all claims arising out of or based upon your Website. No link(s) may appear on any page on your Web site or within any context containing content or materials that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.</span></span></p>
                     <p _ngcontent-giu-c1=""><br _ngcontent-giu-c1=""></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 11 - CONFIDENTIALITY:</strong></u></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""> Unless the relevant party has the prior written consent of the other or unless required to do so by law: (i) All confidential information obtained in connection with these terms, must be preserved. No confidential information will be disclosed or made available to any person, or used for benefit, other than as contemplated by these terms, without the prior written consent of the other. (ii) Each party's obligations under this clause will survive termination of these terms. (iii) These provisions shall not apply to any information which is or becomes public knowledge other than by a breach of this clause; is received from a third party who acquires it legally and is under no disclosure restrictions; is independently developed without access to the confidential information</span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 12 - PERSONAL INFORMATION</strong></u></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Our Privacy Policy, available at [</span><span _ngcontent-giu-c1=""><em _ngcontent-giu-c1="">Insert Link</em></span><span _ngcontent-giu-c1="">] governs your submission of personal information through the store. </span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 13 - ERRORS, INACCURACIES AND OMISSIONS</strong></u></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Occasionally, there may be information on our Platform</span><span _ngcontent-giu-c1="">that contains typographical errors, inaccuracies or omissions. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any of such information is inaccurate at any time without prior notice (including after you have submitted your order).</span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">We undertake no obligation to update, amend or clarify information on our Platform, including without limitation, pricing information, except as required by law. No specified update or refresh date applied on the Platform should be taken to indicate that all information on the Platform has been modified or updated.</span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 14 - PROHIBITED USES</strong></u></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">In addition to other prohibitions as set forth in these Terms, you are prohibited from using the Platform or its content: (a) for any unlawful</span><span _ngcontent-giu-c1=""> purpose</span><span _ngcontent-giu-c1="">; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Platform or of any related Render Health platform; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service</span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">We reserve the right to terminate your use of the platform for violating any of the prohibited uses.</span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 15 - </strong></u></span><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SEVERABILITY</strong></u></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">In the event that</span><span _ngcontent-giu-c1=""> any provision of </span><span _ngcontent-giu-c1="">these Terms</span><span _ngcontent-giu-c1=""> of </span><span _ngcontent-giu-c1="">Service is determined </span><span _ngcontent-giu-c1="">to be </span><span _ngcontent-giu-c1="">unlawful, void or </span><span _ngcontent-giu-c1="">unenforceable</span><span _ngcontent-giu-c1="">,</span><span _ngcontent-giu-c1=""> such provision shall be </span><span _ngcontent-giu-c1="">deemed to be severed</span><span _ngcontent-giu-c1=""> from </span><span _ngcontent-giu-c1="">these Terms of Service but shall not affect the validity</span><span _ngcontent-giu-c1=""> and </span><span _ngcontent-giu-c1="">enforceability</span><span _ngcontent-giu-c1=""> of the </span><span _ngcontent-giu-c1="">other remaining provisions.</span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 16 - ENTIRE AGREEMENT</strong></u></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Any failure by us to exercise or enforce any right or </span><span _ngcontent-giu-c1="">provision </span><span _ngcontent-giu-c1="">contained in these Terms of Service shall not constitute a waiver of such right or provision.</span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">These Terms of Service</span><span _ngcontent-giu-c1=""> and </span><span _ngcontent-giu-c1="">any policies or operating rules posted by us on the Platform constitutes the entire agreement and understanding between you and us and govern your use of our services, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of the Terms of Service).</span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 17 - GOVERNING LAW</strong></u></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">These Terms of Service </span><span _ngcontent-giu-c1="">shall be </span><span _ngcontent-giu-c1="">governed by and construed by the laws of the Federal Republic of Nigeria and</span><span _ngcontent-giu-c1=""> shall be </span><span _ngcontent-giu-c1="">enforced therein</span><span _ngcontent-giu-c1="">.</span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 18 - CHANGES TO THESE TERMS OF SERVICE</strong></u></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">You can review the most current version of these Terms of Service at any time on this page.</span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">We reserve the right, at our sole discretion, to update, change or replace any part of these Terms by posting updates and changes to our Platform. It is your responsibility to check our platform periodically for changes. Your continued use of or access to our Platform or any of our services following the posting of any changes to these Terms of Service constitutes acceptance of those changes.</span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">SECTION 19 - </strong></u></span><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><strong _ngcontent-giu-c1="">CONTACT INFORMATION</strong></u></span></p>
                     <p _ngcontent-giu-c1=""><span _ngcontent-giu-c1="">Questions about the Terms of Service should be sent to us at: </span><span _ngcontent-giu-c1=""><u _ngcontent-giu-c1=""><a _ngcontent-giu-c1="" href="mailto:contact@renderhealth.com"><span _ngcontent-giu-c1="">contact@renderhealth.com</span></a></u></span></p>
                     <p _ngcontent-giu-c1=""><br _ngcontent-giu-c1=""></p>
                     <p _ngcontent-giu-c1="">&nbsp;</p>
                     <p _ngcontent-giu-c1="">&nbsp;</p>

                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<?php include("footer.php"); ?>